/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_thinkingdata_analytics_TDAnalyticsCocosAPI */

#ifndef _Included_cn_thinkingdata_analytics_TDAnalyticsCocosAPI
#define _Included_cn_thinkingdata_analytics_TDAnalyticsCocosAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_thinkingdata_analytics_TDAnalyticsCocosAPI
 * Method:    getDynamicPropertiesJson
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_thinkingdata_analytics_TDAnalyticsCocosAPI_getDynamicPropertiesJson
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
